# action.yml
name: 'Hello World'
description: 'Custom greet with golang program'
author: 'Someone'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
   secret:
    description: 'server secret for component'
    required: true
