# action.yml
name: 'Hello World'
description: 'Custom greet with golang program'
author: 'Someone'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
   login:
    description: 'client login'
    required: true
   pass:
     description: 'client password'
     required: true
   server_ip:
     description: 'ip of the server to, to change in hosts file'
     required: true
   server_domain:
     description: 'server domain that serves as jid domain part for the client too'
     required: true