on: [push]
jobs:
  hello-script:
    runs-on: ubuntu-latest
    name: hello only using bash script for now
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: echo action step
        id: hello
        uses: ./
        with: # Set the secret as an input
          login: ${{ secrets.bot_username }}
          pass: ${{ secrets.bot_password }}
          server_domain: ${{ secrets.server_domain}}
          correspondant: ${{ secrets.correspondant}}
          server_port: ${{ secrets.server_port }}
