on:
  push:
    branches:
      - master
  pull_request:
     branches:
       - master
jobs:
  notif-script:
    runs-on: ubuntu-latest
    name: workflow that pushes repo news to xmpp server
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: push_info_step
        id: push
        uses: ./
        if: github.event_name == 'push'
        with: # Set the secrets as inputs
          login: ${{ secrets.bot_username }}
          pass: ${{ secrets.bot_password }}
          server_domain: ${{ secrets.server_rooms_domain }}
          correspondant: ${{ secrets.room_correspondent }}
          server_port: ${{ secrets.server_port }}
          message: |
            ${{ github.actor }} pushed ${{ github.event.ref }} ${{ github.event.compare }} with message:
            ${{ join(github.event.commits.*.message) }}
          correspondent_is_room: true
      - name: pr_info_step
        id: pull_request
        uses: ./
        if: github.event_name == 'pull_request'
        with: # Set the secrets as inputs
          login: ${{ secrets.bot_username }}
          pass: ${{ secrets.bot_password }}
          server_domain: ${{ secrets.server_domain}}
          correspondant: ${{ secrets.single_user_correspondent}}
          server_port: ${{ secrets.server_port }}
          message: |
            ${{ github.actor }} opened a PR ${{ github.event.html_url }}
          correspondent_is_room: false
