on: [push]
jobs:
  hello-script:
    runs-on: ubuntu-latest
    name: hello only using bash script for now
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: echo action step
        id: hello
        uses: ./
        with: # Set the secret as an input
          secret: ${{ secrets.Ejabberd_component }}
